### ISSUE TITLE
key() not available after calling await ref.push()

### ISSUE THREAD

**Issue by KevinGrandon** [casetext/fireproof#24]
After reading the Firebase docs and playing with this repo, I would expect the following to work, but it seems not to:

``` js
var ref = fp.child('myref')
var record = await ref.push({ /* some object */})
console.log(record.key()) // This is undefined
```

I haven't dug into the code yet, but will do so soon. If this does work, please update the README with an example, thanks!

**Comment by goldibex** [comment]
Hi @KevinGrandon, thanks for the report.

Here's what's happening:

The behavior of the Fireproof `push` method (and the underlying Firebase `push` operation) is a bit elaborate. The bottom line is that it _synchronously_ returns a reference to the newly created location, because the push key is generated directly by the client, not the server.

In Fireproof, the synchronously-created reference is also a promise that resolves or rejects on the `push` operation from the server-side.

So if you want the key of the newly pushed location, there's no need for an `await` here. What you want is:

``` js
var ref = fp.child('myref')
var pushref = ref.push({ /* some object */})
console.log(record.key()) // This is the key of the newly pushed location
var error = await pushref
if (error) {
  console.error('Something went wrong pushing ' + record.key())
  console.error(error)
}
```

**Comment by KevinGrandon** [comment]
Thank you for the detailed and quick response! Mind if I submit a pull request to update the README?
